# Generated by Django 4.0.2 on 2022-02-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default='https://media.istockphoto.com/photos/pop-it-pikachu-pokemon-on-dark-background-picture-id1339486581', upload_to='media/'),
        ),
    ]
