# Generated by Django 4.0.2 on 2022-02-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oro', '0002_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='https://media.istockphoto.com/photos/pop-it-pikachu-pokemon-on-dark-background-picture-id1339486581', upload_to=''),
        ),
    ]
